# Generated by Django 6.0.5 on 2026-05-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventurerscodexapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='ability_score_increases',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='race',
            name='traits',
            field=models.TextField(default=''),
        ),
    ]
