# Generated by Django 6.0.5 on 2026-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventurerscodexapi', '0002_race_ability_score_increases_race_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hit_die', models.CharField(default='', max_length=5)),
                ('primary_ability', models.CharField(default='', max_length=100)),
                ('saving_throw_proficiencies', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
