# Generated by Django 6.0.5 on 2026-05-15 18:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventurerscodexapi', '0004_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('subclass', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='adventurerscodexapi.character')),
                ('dnd_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adventurerscodexapi.dndclass')),
            ],
            options={
                'unique_together': {('character', 'dnd_class')},
            },
        ),
    ]
