# Generated by Django 6.0.5 on 2026-05-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventurerscodexapi', '0006_populate_character_class_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='dnd_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
    ]
